### PR TITLE
fix: Update input to empty string when `userValue` is `undefined`

### LINKED ISSUE #322: Input value doesn't update when prop `value` is set to `undefined` from an external button
**Describe the bug**
When the input value is changed to `undefined` from a button, CurrencyInput doesn't update accordingly.

**To Reproduce**
1. Go to [the sandbox](https://codesandbox.io/p/sandbox/quizzical-payne-zpttwy?file=%2Fsrc%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqe24q9400063b6hrmiy3xam%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqe24q9400023b6hklcr78ei%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqe24q9400033b6hoozsxe5u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqe24q9400053b6hlwplxs5p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqe24q9400023b6hklcr78ei%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqe24q9400013b6h6pzniadf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqe2d5y200j53b6hansyyx09%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A24%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqe24q9400023b6hklcr78ei%2522%252C%2522activeTabId%2522%253A%2522clqe2d5y200j53b6hansyyx09%2522%257D%252C%2522clqe24q9400053b6hlwplxs5p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqe24q9400043b6hqlw1t1ut%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqe24q9400053b6hlwplxs5p%2522%252C%2522activeTabId%2522%253A%2522clqe24q9400043b6hqlw1t1ut%2522%257D%252C%2522clqe24q9400033b6hoozsxe5u%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqe24q9400033b6hoozsxe5u%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) illustrating the issue.
2. Notice how `value` is set to `undefined` by default.
3. Enter a number in the input field
4. Notice how `value` updates accordingly
5. Click the "Reset" button that will set `value` to `undefined` again.
6. Notice how `CurrenyInput` is showing a stale value.

**Expected behavior**
I expect `CurrencyInput` to be blank when `value` is set to `undefined`.

**Code Sandbox**
CodeSandbox [example](https://codesandbox.io/p/sandbox/quizzical-payne-zpttwy?file=%2Fsrc%2FApp.js&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqe24q9400063b6hrmiy3xam%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqe24q9400023b6hklcr78ei%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqe24q9400033b6hoozsxe5u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqe24q9400053b6hlwplxs5p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqe24q9400023b6hklcr78ei%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqe24q9400013b6h6pzniadf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqe2d5y200j53b6hansyyx09%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A24%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A24%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqe24q9400023b6hklcr78ei%2522%252C%2522activeTabId%2522%253A%2522clqe2d5y200j53b6hansyyx09%2522%257D%252C%2522clqe24q9400053b6hlwplxs5p%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqe24q9400043b6hqlw1t1ut%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqe24q9400053b6hlwplxs5p%2522%252C%2522activeTabId%2522%253A%2522clqe24q9400043b6hqlw1t1ut%2522%257D%252C%2522clqe24q9400033b6hoozsxe5u%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqe24q9400033b6hoozsxe5u%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Additional context**
When `undefined` is set from an external source, CurrencyInput doesn't react to it. See those screenshots from the Chrome extension [React Developer Tools](https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?pli=1).

### When `value` prop is set by CurrencyInput via `onValueChange`
Screen Shot 2023-12-20 at 9 51 21 AM

### When `value` prop is set to `undefined` via external button
Screen Shot 2023-12-20 at 9 51 39 AM

### PR DESCRIPTION
**Pull request by aconrad**
Fixes #322.

I'm unsure if that's the correct approach, but all tests pass, including the ones I added that weren't passing before the fix.

### CODE REVIEW

File: src/components/CurrencyInput.tsx [hunk 1]
```diff
@@ -104,9 +104,9 @@ export const CurrencyInput: FC<CurrencyInputProps> = forwardRef<
     };
 
     const formattedStateValue =
-      defaultValue !== undefined && defaultValue !== null
+      defaultValue != null
```
Comment (aconrad) [inline src/components/CurrencyInput.tsx:107]: This is just a clean-up. The double-equal null logic is equivalent to checking for `null` and `undefined`. It makes the code more concise.

**Comment by aconrad** [comment]
@cchanxzy do you have time to take a look at this PR and the issue it attempts to fix?

**Comment by cchanxzy** [comment]
Thanks for the contribution and fix @aconrad !

File: src/components/CurrencyInput.tsx (hunk 1 above)
Comment (cchanxzy) [reply src/components/CurrencyInput.tsx:107]: Interesting, I did not know that!

Although, I personally would prefer to be explicit rather than concise, so I was tempted to say keep it as is, but since all the tests passed anyway, I thought that's good enough for me :D
